Added s3 module
sourcefuse/terraform-aws-arc-s3 pull request #1
Opened 2024-06-27 13:20 UTC by mayank0202

## Description

Added s3 module

<img width="955" alt="Screenshot 2024-06-27 at 7 07 32 PM" src="https://github.com/sourcefuse/terraform-aws-arc-s3/assets/83959396/baa40522-d037-431a-93fe-ddc2dbf8a732">

## Checklist

Please ensure that the following steps are completed before submitting the pull request:

- [x] Code follows the Terraform best practices and style guidelines.
- [x] Changes are appropriately documented, including any necessary updates to README or other documentation files.
- [ ] Unit tests have been added or updated to cover the changes introduced by this pull request.
- [x] Changes have been tested locally and verified to work as expected.
- [x] The code has been reviewed to ensure it aligns with the project's goals and standards.
- [ ] Dependencies and backward compatibility have been considered and addressed if applicable.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Testing Instructions

ran terraform apply in example folder

2024-06-27 13:44 UTC, tsaucier-sf approved these changes

2024-06-27 14:07 UTC, vijay-stephen requested changes

2024-06-27 14:07 UTC, vijay-stephen commented on locals.tf
> +  bucket_id           = join("", aws_s3_bucket.this[*].id)
`join` is deprecated, please remove

2024-06-27 14:07 UTC, vijay-stephen commented on locals.tf
> +  object_lock_enabled = var.enabled && var.object_lock_configuration != null
try to avoid having `enabled` variable

2024-06-27 14:07 UTC, vijay-stephen commented on locals.tf
> +  bucket_arn          = "arn:${local.partition}:s3:::${local.bucket_id}"
bucket_arn local variable is required?

2024-06-27 14:07 UTC, vijay-stephen commented on variables.tf
> +
please remove this variable

2024-06-27 14:08 UTC, vijay-stephen commented
@mayank0202 Add an example for CRR or SRR

2024-07-03 16:58 UTC, mayank0202 commented on locals.tf
> +  bucket_arn          = "arn:${local.partition}:s3:::${local.bucket_id}"
bucket_arn is used for bucket policy . You can check the data file @vijay-stephen

2024-07-30 08:33 UTC, closed without merging